const PERMITTED_TICKET_TYPES = ['ADULT', 'CHILD', 'INFANT']
const MAXIMUM_TICKET_LIMIT = 20;
const TICKET_PRICE_LIST = Object.freeze({
  ADULT: 20,
  CHILD: 10,
  INFANT: 0
})

export { PERMITTED_TICKET_TYPES, TICKET_PRICE_LIST, MAXIMUM_TICKET_LIMIT }
